package renderers;

public enum Noise {
	PERLIN, SIMPLEX, SCALES, SQUARES, TRIANGLES, WOOD,
	ADV_PERLIN, ADV_SIMPLEX, ADV_SCALES, ADV_SQUARES, ADV_TRIANGLES, ADV_WOOD
	/*
	PERLIN2D, SIMPLEX2D, SCALES2D, SQUARES2D, TRIANGLES2D, WOOD2D,
	ADVPERLIN2D, ADVSIMPLEX2D, ADVSCALES2D, ADVSQUARES2D, ADVTRIANGLES2D, ADVWOOD2D
	*/
}
